sessions = {'pmc_gaba1','pmc_gaba2','pmc_gaba3','pmc_gaba4','pmc_sal2',...
    'pmc_acsf1','pmc_acsf2','pmc_noic1','pmc_noic2','pmc_noic4',...
    'put_gaba','put_noic1','put_noic2','put_noic3'};
session_tag = [1,1,1,1,2,2,2,3,3,3,4,5,5,5];


%%
all_before_complete = [];
all_before_incomplete = [];
all_before_correct = [];
all_before_predicted = [];
all_before_unpredicted = [];
all_before_reaction_time = [];
all_before_left_accurate = [];
all_before_left_inaccurate = [];
all_before_right_accurate = [];
all_before_right_inaccurate = [];
all_before_lr_bias = [];

all_correct = [];

for n = 1:length(sessions)
    session = sessions{n};
    load(session,'task_info','infusion');
    if session_tag(n)==3 || session_tag(n)==5
        start_inject = 10*60;
        end_inject = 10*60;
    else
        start_inject = infusion.start;
        end_inject = infusion.end;
    end
    
    varnames = fieldnames(task_info);
    for v = 1:length(varnames)
        eval([varnames{v},'=task_info.',varnames{v},';']);
    end

    time = [0:1/fs_task:(trials(2,end)/fs_task+100)];
    trial_times = [time(trials(1,:));time(trials(2,:))];
    trial_ind = mean(trials);

    samples(:,complete_trials==0) = [];
    sample_id(complete_trials==0) = [];
    rewarded_trials(complete_trials==0) = [];
    correct_trials(complete_trials==0) = [];
    correct_loc(complete_trials==0) = [];
    left = (correct_loc==11).*(correct_trials==1);
    left(((correct_loc==12).*(correct_trials==0))==1)=1;
    right = (correct_loc==12).*(correct_trials==1);
    right(((correct_loc==11).*(correct_trials==0))==1)=1;
    left = left==1;
    right = right==1;
    trials(:,complete_trials==0) = [];
    predicted(complete_trials==0) = [];
    incomplete_trials = complete_trials==0; % do not include trials without initial fixation
    reaction_time(complete_trials==0) = [];
    
    trials_complete = trials;
    trial_times_complete = trial_times;
    trial_ind = mean(trials);

    correct_predicted = correct_trials(predicted==1);
    correct_unpredicted = correct_trials(predicted==0);
    
    before_trials = (trial_times(2,:)<start_inject(1))';
    before_trials_complete = before_trials(complete_trials==1);
    before_trials_predicted = before_trials_complete(predicted==1);
    before_trials_unpredicted = before_trials_complete(predicted==0);
    
    before_trials_leftcued = (before_trials_complete.*(correct_loc==11))==1;
    before_trials_rightcued = (before_trials_complete.*(correct_loc==12))==1;
    [before_trials_leftcued,before_trials_rightcued] = ...
        balanced_lr_cue(before_trials_complete,correct_loc);
    before_lr_bias = -1*((before_trials_leftcued).*left)+...
        ((before_trials_rightcued).*right); 
    before_lr_bias = before_lr_bias((before_trials_leftcued+...
        before_trials_rightcued)==1);     

    
    all_before_complete = [all_before_complete;...
        complete_trials((before_trials.*(nofix==0))==1)];
    all_before_reaction_time = [all_before_reaction_time;...
        reaction_time(before_trials_complete)];
    all_before_lr_bias = [all_before_lr_bias; before_lr_bias];
    
    all_before_correct = [all_before_correct;...
        correct_trials(before_trials_complete)];
    all_before_predicted = [all_before_predicted;...
        correct_predicted(before_trials_predicted)];
    all_before_unpredicted = [all_before_unpredicted;...
        correct_unpredicted(before_trials_unpredicted)];
    
    all_correct = [all_correct;...
        correct_trials];
   
end



all_before_complete_p = ...
    [sum(all_before_complete)/length(all_before_complete),...
    binomial_ci_bs(all_before_complete)];
all_before_correct_p = ...
    [sum(all_before_correct)/length(all_before_correct),...
    binomial_ci_bs(all_before_correct)];
all_before_predicted_p = ...
    [sum(all_before_predicted)/length(all_before_predicted),...
    binomial_ci_bs(all_before_predicted)];
all_before_unpredicted_p = ...
    [sum(all_before_unpredicted)/length(all_before_unpredicted),...
    binomial_ci_bs(all_before_unpredicted)];

all_correct_p = [sum(all_correct)/length(all_correct),...
    binomial_ci_bs(all_correct)];

%%
session_stats = cell(length(sessions),1);
for n = 1:length(sessions)
    session = sessions{n};
    load(session,'task_info','infusion');
    if session_tag(n)==3 || session_tag(n)==5
        start_inject = 10*60;
        end_inject = 10*60;
    else
        start_inject = infusion.start;
        end_inject = infusion.end;
    end
    
    varnames = fieldnames(task_info);
    for v = 1:length(varnames)
        eval([varnames{v},'=task_info.',varnames{v},';']);
    end

    time = [0:1/fs_task:(trials(2,end)/fs_task+100)];

    trial_times = [time(trials(1,:));time(trials(2,:))];

    samples(:,complete_trials==0) = [];
    sample_id(complete_trials==0) = [];
    rewarded_trials(complete_trials==0) = [];
    correct_trials(complete_trials==0) = [];
    correct_loc(complete_trials==0) = [];
    left = (correct_loc==11).*(correct_trials==1);
    left(((correct_loc==12).*(correct_trials==0))==1)=1;
    right = (correct_loc==12).*(correct_trials==1);
    right(((correct_loc==11).*(correct_trials==0))==1)=1;
    left = left==1;
    right = right==1;
    trials(:,complete_trials==0) = [];
    predicted(complete_trials==0) = [];
    reaction_time(complete_trials==0) = [];
    
    trials_complete = trials;
    trial_times_complete = trial_times;
    trial_ind = mean(trials);

    correct_predicted = correct_trials(predicted==1);
    correct_unpredicted = correct_trials(predicted==0);

    behavior_stats = struct;

    behavior_stats.accuracy_all = [sum(correct_trials)/...
        length(correct_trials),binomial_ci_bs(correct_trials)];
    behavior_stats.accuracy_predicted = [sum(correct_predicted)...
        /length(correct_predicted),...
        binomial_ci_bs(correct_predicted)];
    behavior_stats.accuracy_unpredicted = [sum(correct_unpredicted)...
        /length(correct_unpredicted),...
        binomial_ci_bs(correct_unpredicted)];
    behavior_stats.complete_all = [sum(complete_trials)/...
        length(complete_trials),...
        binomial_ci_bs(complete_trials)];
    
    before_trials = (trial_times(2,:)<start_inject(1))';
    after_trials = (trial_times(1,:)>end_inject(end))';
    inhib_trials = (((trial_times(1,:)>end_inject(end)).*...
        (trial_times(1,:)<(end_inject(end)+10*60)))==1)';
    recov_trials = (trial_times(1,:)>(end_inject(end)+20*60))';
    during_trials = ((before_trials+after_trials) == 0);
    
    before_trials_complete = before_trials(complete_trials==1);
    after_trials_complete = after_trials(complete_trials==1);
    inhib_trials_complete = inhib_trials(complete_trials==1);
    recov_trials_complete = recov_trials(complete_trials==1);
    during_trials_complete = during_trials(complete_trials==1);
    
    behavior_stats.n_before_trials_complete = sum(before_trials_complete);
    behavior_stats.n_after_trials_complete = sum(after_trials_complete);
    behavior_stats.n_inhib_trials_complete = sum(inhib_trials_complete);
    behavior_stats.n_recov_trials_complete = sum(recov_trials_complete);
    behavior_stats.n_during_trials_complete = sum(during_trials_complete);
    
    before_trials_leftcued = (before_trials_complete.*(correct_loc==11))==1;
    after_trials_leftcued = (after_trials_complete.*(correct_loc==11))==1;
    inhib_trials_leftcued = (inhib_trials_complete.*(correct_loc==11))==1;
    recov_trials_leftcued = (recov_trials_complete.*(correct_loc==11))==1;
    during_trials_leftcued = (during_trials_complete.*(correct_loc==11))==1;
    
    before_trials_rightcued = (before_trials_complete.*(correct_loc==12))==1;
    after_trials_rightcued = (after_trials_complete.*(correct_loc==12))==1;
    inhib_trials_rightcued = (inhib_trials_complete.*(correct_loc==12))==1;
    recov_trials_rightcued = (recov_trials_complete.*(correct_loc==12))==1;
    during_trials_rightcued = (during_trials_complete.*(correct_loc==12))==1;
    
    behavior_stats.n_before_trials_leftcued = sum(before_trials_leftcued);
    behavior_stats.n_after_trials_leftcued = sum(after_trials_leftcued);
    behavior_stats.n_inhib_trials_leftcued = sum(inhib_trials_leftcued);
    behavior_stats.n_recov_trials_leftcued = sum(recov_trials_leftcued);
    behavior_stats.n_during_trials_leftcued = sum(during_trials_leftcued);
    
    behavior_stats.n_before_trials_rightcued = sum(before_trials_rightcued);
    behavior_stats.n_after_trials_rightcued = sum(after_trials_rightcued);
    behavior_stats.n_inhib_trials_rightcued = sum(inhib_trials_rightcued);
    behavior_stats.n_recov_trials_rightcued = sum(recov_trials_rightcued);
    behavior_stats.n_during_trials_rightcued = sum(during_trials_rightcued);
    
    % balance l and r cued
    [before_trials_leftcued_even,before_trials_rightcued_even] = ...
        balanced_lr_cue(before_trials_complete,correct_loc);
    before_lr_bias = -1*((before_trials_leftcued_even).*left)+...
        ((before_trials_rightcued_even).*right); 
    before_lr_bias = before_lr_bias((before_trials_leftcued_even+...
        before_trials_rightcued_even)==1);
    
    [after_trials_leftcued_even,after_trials_rightcued_even] = ...
        balanced_lr_cue(after_trials_complete,correct_loc);
    after_lr_bias = -1*((after_trials_leftcued_even).*left)+...
        ((after_trials_rightcued_even).*right); 
    after_lr_bias = after_lr_bias((after_trials_leftcued_even+...
        after_trials_rightcued_even)==1);
    
    [inhib_trials_leftcued_even,inhib_trials_rightcued_even] = ...
        balanced_lr_cue(inhib_trials_complete,correct_loc);
    inhib_lr_bias = -1*((inhib_trials_leftcued_even).*left)+...
        ((inhib_trials_rightcued_even).*right); 
    inhib_lr_bias = inhib_lr_bias((inhib_trials_leftcued_even+...
        inhib_trials_rightcued_even)==1);
    
    [recov_trials_leftcued_even,recov_trials_rightcued_even] = ...
        balanced_lr_cue(recov_trials_complete,correct_loc);
    recov_lr_bias = -1*((recov_trials_leftcued_even).*left)+...
        ((recov_trials_rightcued_even).*right); 
    recov_lr_bias = recov_lr_bias((recov_trials_leftcued_even+...
        recov_trials_rightcued_even)==1);
    
    [during_trials_leftcued_even,during_trials_rightcued_even] = ...
        balanced_lr_cue(during_trials_complete,correct_loc);
    during_lr_bias = -1*((during_trials_leftcued_even).*left)+...
        ((during_trials_rightcued_even).*right); 
    during_lr_bias = during_lr_bias((during_trials_leftcued_even+...
        during_trials_rightcued_even)==1);
    
    before_trials_predicted = before_trials_complete(predicted==1);
    after_trials_predicted = after_trials_complete(predicted==1);
    inhib_trials_predicted = inhib_trials_complete(predicted==1);
    recov_trials_predicted = recov_trials_complete(predicted==1);
    during_trials_predicted = during_trials_complete(predicted==1);
    
    before_trials_unpredicted = before_trials_complete(predicted==0);
    after_trials_unpredicted = after_trials_complete(predicted==0);
    inhib_trials_unpredicted = inhib_trials_complete(predicted==0);
    recov_trials_unpredicted = recov_trials_complete(predicted==0);
    during_trials_unpredicted = during_trials_complete(predicted==0);

    % Do not include trials without initial fixation
    behavior_stats.complete.before = ...
        [sum(complete_trials((before_trials.*(nofix==0))==1))...
        ./sum((before_trials.*(nofix==0))==1),...
        binomial_ci_bs(complete_trials((before_trials.*(nofix==0))==1))];
    behavior_stats.complete.after = ...
        [sum(complete_trials((after_trials.*(nofix==0))==1))...
        ./sum((after_trials.*(nofix==0))==1),...
        binomial_ci_bs(complete_trials((after_trials.*(nofix==0))==1))];
    behavior_stats.complete.inhib = ...
        [sum(complete_trials((inhib_trials.*(nofix==0))==1))...
        ./sum((inhib_trials.*(nofix==0))==1),...
        binomial_ci_bs(complete_trials((inhib_trials.*(nofix==0))==1))];
    behavior_stats.complete.recov = ...
        [sum(complete_trials((recov_trials.*(nofix==0))==1))...
        ./sum((recov_trials.*(nofix==0))==1),...
        binomial_ci_bs(complete_trials((recov_trials.*(nofix==0))==1))];
    behavior_stats.complete.during = ...
        [sum(complete_trials((during_trials.*(nofix==0))==1))...
        ./sum((during_trials.*(nofix==0))==1),...
        binomial_ci_bs(complete_trials((during_trials.*(nofix==0))==1))];
    
    behavior_stats.complete.diff.after = ...
        [binomial_compare_bs(complete_trials((before_trials.*(nofix==0))==1),...
        complete_trials((after_trials.*(nofix==0))==1))];
    behavior_stats.complete.diff.inhib = ...
        [binomial_compare_bs(complete_trials((before_trials.*(nofix==0))==1),...
        complete_trials((inhib_trials.*(nofix==0))==1))];
    behavior_stats.complete.diff.recov = ...
        [binomial_compare_bs(complete_trials((before_trials.*(nofix==0))==1),...
        complete_trials((recov_trials.*(nofix==0))==1))];
    behavior_stats.complete.diff.during = ...
        [binomial_compare_bs(complete_trials((before_trials.*(nofix==0))==1),...
        complete_trials((during_trials.*(nofix==0))==1))];
    
    behavior_stats.complete.diff.all.after = ...
        [binomial_compare_bs(all_before_complete,...
        complete_trials((after_trials.*(nofix==0))==1))];
    behavior_stats.complete.diff.all.inhib = ...
        [binomial_compare_bs(all_before_complete,...
        complete_trials((inhib_trials.*(nofix==0))==1))];
    behavior_stats.complete.diff.all.recov = ...
        [binomial_compare_bs(all_before_complete,...
        complete_trials((recov_trials.*(nofix==0))==1))];
    behavior_stats.complete.diff.all.during = ...
        [binomial_compare_bs(all_before_complete,...
        complete_trials((during_trials.*(nofix==0))==1))];
    

    
    
    behavior_stats.accuracy.before = ...
        [sum(correct_trials(before_trials_complete))...
        ./sum(before_trials_complete),...
        binomial_ci_bs(correct_trials(before_trials_complete))];
    behavior_stats.accuracy.after = ...
        [sum(correct_trials(after_trials_complete))...
        ./sum(after_trials_complete),...
        binomial_ci_bs(correct_trials(after_trials_complete))];
    behavior_stats.accuracy.inhib = ...
        [sum(correct_trials(inhib_trials_complete))...
        ./sum(inhib_trials_complete),...
        binomial_ci_bs(correct_trials(inhib_trials_complete))];
    behavior_stats.accuracy.recov = ...
        [sum(correct_trials(recov_trials_complete))...
        ./sum(recov_trials_complete),...
        binomial_ci_bs(correct_trials(recov_trials_complete))];
    behavior_stats.accuracy.during = ...
        [sum(correct_trials(during_trials_complete))...
        ./sum(during_trials_complete),...
        binomial_ci_bs(correct_trials(during_trials_complete))];
    
    behavior_stats.accuracy.diff.after = ...
        [binomial_compare_bs(correct_trials(before_trials_complete),...
        correct_trials(after_trials_complete))];
    behavior_stats.accuracy.diff.inhib = ...
        [binomial_compare_bs(correct_trials(before_trials_complete),...
        correct_trials(inhib_trials_complete))];
    behavior_stats.accuracy.diff.recov = ...
        [binomial_compare_bs(correct_trials(before_trials_complete),...
        correct_trials(recov_trials_complete))];
    behavior_stats.accuracy.diff.during = ...
        [binomial_compare_bs(correct_trials(before_trials_complete),...
        correct_trials(during_trials_complete))];
    
    behavior_stats.accuracy.diff.all.before = ...
        [binomial_compare_bs(all_before_correct,...
        correct_trials(before_trials_complete))];
    behavior_stats.accuracy.diff.all.after = ...
        [binomial_compare_bs(all_before_correct,...
        correct_trials(after_trials_complete))];
    behavior_stats.accuracy.diff.all.inhib = ...
        [binomial_compare_bs(all_before_correct,...
        correct_trials(inhib_trials_complete))];
    behavior_stats.accuracy.diff.all.recov = ...
        [binomial_compare_bs(all_before_correct,...
        correct_trials(recov_trials_complete))];
    behavior_stats.accuracy.diff.all.during = ...
        [binomial_compare_bs(all_before_correct,...
        correct_trials(during_trials_complete))];
    
    %%%%%%%%%
    
    behavior_stats.reaction_time.before = ...
        [sum(reaction_time(before_trials_complete))...
        ./sum(before_trials_complete),...
        binomial_ci_bs(reaction_time(before_trials_complete))];
    behavior_stats.reaction_time.after = ...
        [sum(reaction_time(after_trials_complete))...
        ./sum(after_trials_complete),...
        binomial_ci_bs(reaction_time(after_trials_complete))];
    behavior_stats.reaction_time.inhib = ...
        [sum(reaction_time(inhib_trials_complete))...
        ./sum(inhib_trials_complete),...
        binomial_ci_bs(reaction_time(inhib_trials_complete))];
    behavior_stats.reaction_time.recov = ...
        [sum(reaction_time(recov_trials_complete))...
        ./sum(recov_trials_complete),...
        binomial_ci_bs(reaction_time(recov_trials_complete))];
    behavior_stats.accuracy.during = ...
        [sum(reaction_time(during_trials_complete))...
        ./sum(during_trials_complete),...
        binomial_ci_bs(reaction_time(during_trials_complete))];
    
    behavior_stats.reaction_time.diff.after = ...
        [binomial_compare_bs(reaction_time(before_trials_complete),...
        reaction_time(after_trials_complete))];
    behavior_stats.reaction_time.diff.inhib = ...
        [binomial_compare_bs(reaction_time(before_trials_complete),...
        reaction_time(inhib_trials_complete))];
    behavior_stats.reaction_time.diff.recov = ...
        [binomial_compare_bs(reaction_time(before_trials_complete),...
        reaction_time(recov_trials_complete))];
    behavior_stats.reaction_time.diff.during = ...
        [binomial_compare_bs(reaction_time(before_trials_complete),...
        reaction_time(during_trials_complete))];
    
    behavior_stats.reaction_time.diff.all.before = ...
        [binomial_compare_bs(all_before_reaction_time,...
        reaction_time(before_trials_complete))];
    behavior_stats.reaction_time.diff.all.after = ...
        [binomial_compare_bs(all_before_reaction_time,...
        reaction_time(after_trials_complete))];
    behavior_stats.reaction_time.diff.all.inhib = ...
        [binomial_compare_bs(all_before_reaction_time,...
        reaction_time(inhib_trials_complete))];
    behavior_stats.reaction_time.diff.all.recov = ...
        [binomial_compare_bs(all_before_reaction_time,...
        reaction_time(recov_trials_complete))];
    behavior_stats.reaction_time.diff.all.during = ...
        [binomial_compare_bs(all_before_reaction_time,...
        reaction_time(during_trials_complete))];
    %%%%%%%%%%%%

    %%%%%%%%%
    % difference in left vs. right correct (accuracy would be value x 2)
    behavior_stats.lr_bias.before = ...
        [sum(before_lr_bias)./length(before_lr_bias),...
        binomial_ci_bs(before_lr_bias)]; 
    behavior_stats.lr_bias.after = ...
        [sum(after_lr_bias)./length(after_lr_bias),...
        binomial_ci_bs(after_lr_bias)];
    behavior_stats.lr_bias.inhib = ...
        [sum(inhib_lr_bias)./length(inhib_lr_bias),...
        binomial_ci_bs(inhib_lr_bias)];
    behavior_stats.lr_bias.recov = ...
        [sum(recov_lr_bias)./length(recov_lr_bias),...
        binomial_ci_bs(recov_lr_bias)];
    behavior_stats.lr_bias.during = ...
        [sum(during_lr_bias)./length(during_lr_bias),...
        binomial_ci_bs(during_lr_bias)];
    
    behavior_stats.lr_bias.diff.after = ...
        [binomial_compare_bs(before_lr_bias,after_lr_bias)];
    behavior_stats.lr_bias.diff.inhib = ...
        [binomial_compare_bs(before_lr_bias,inhib_lr_bias)];
    behavior_stats.lr_bias.diff.recov = ...
        [binomial_compare_bs(before_lr_bias,recov_lr_bias)];
    behavior_stats.lr_bias.diff.during = ...
        [binomial_compare_bs(before_lr_bias,during_lr_bias)];
    
    behavior_stats.lr_bias.diff.all.after = ...
        [binomial_compare_bs(all_before_lr_bias,before_lr_bias)];
    behavior_stats.lr_bias.diff.all.after = ...
        [binomial_compare_bs(all_before_lr_bias,after_lr_bias)];
    behavior_stats.lr_bias.diff.all.inhib = ...
        [binomial_compare_bs(all_before_lr_bias,inhib_lr_bias)];
    behavior_stats.lr_bias.diff.all.recov = ...
        [binomial_compare_bs(all_before_lr_bias,recov_lr_bias)];
    behavior_stats.lr_bias.diff.all.during = ...
        [binomial_compare_bs(all_before_lr_bias,during_lr_bias)];
    %%%%%%%%%%%%
    
    behavior_stats.accuracy.predicted.before = ...
        [sum(correct_predicted(before_trials_predicted))...
        ./sum(before_trials_predicted),...
        binomial_ci_bs(correct_predicted(before_trials_predicted))];
    behavior_stats.accuracy.predicted.after = ...
        [sum(correct_predicted(after_trials_predicted))...
        ./sum(after_trials_predicted),...
        binomial_ci_bs(correct_predicted(after_trials_predicted))];
    behavior_stats.accuracy.predicted.inhib = ...
        [sum(correct_predicted(inhib_trials_predicted))...
        ./sum(inhib_trials_predicted),...
        binomial_ci_bs(correct_predicted(inhib_trials_predicted))];
    behavior_stats.accuracy.predicted.recov = ...
        [sum(correct_predicted(recov_trials_predicted))...
        ./sum(recov_trials_predicted),...
        binomial_ci_bs(correct_predicted(recov_trials_predicted))];
    behavior_stats.accuracy.predicted.during = ...
        [sum(correct_predicted(during_trials_predicted))...
        ./sum(during_trials_predicted),...
        binomial_ci_bs(correct_predicted(during_trials_predicted))];
    
    behavior_stats.accuracy.predicted.diff.after = ...
        [binomial_compare_bs(correct_trials(before_trials_predicted),...
        correct_trials(after_trials_predicted))];
    behavior_stats.accuracy.predicted.diff.inhib = ...
        [binomial_compare_bs(correct_trials(before_trials_predicted),...
        correct_trials(inhib_trials_predicted))];
    behavior_stats.accuracy.predicted.diff.recov = ...
        [binomial_compare_bs(correct_trials(before_trials_predicted),...
        correct_trials(recov_trials_predicted))];
    behavior_stats.accuracy.predicted.diff.during = ...
        [binomial_compare_bs(correct_trials(before_trials_predicted),...
        correct_trials(during_trials_predicted))];
    
    behavior_stats.accuracy.predicted.diff.all.before = ...
        [binomial_compare_bs(all_before_predicted,...
        correct_trials(before_trials_predicted))];
    behavior_stats.accuracy.predicted.diff.all.after = ...
        [binomial_compare_bs(all_before_predicted,...
        correct_trials(after_trials_predicted))];
    behavior_stats.accuracy.predicted.diff.all.inhib = ...
        [binomial_compare_bs(all_before_predicted,...
        correct_trials(inhib_trials_predicted))];
    behavior_stats.accuracy.predicted.diff.all.recov = ...
        [binomial_compare_bs(all_before_predicted,...
        correct_trials(recov_trials_predicted))];
    behavior_stats.accuracy.predicted.diff.all.during = ...
        [binomial_compare_bs(all_before_predicted,...
        correct_trials(during_trials_predicted))];
    
    behavior_stats.accuracy.unpredicted.before = ...
        [sum(correct_unpredicted(before_trials_unpredicted))...
        ./sum(before_trials_unpredicted),...
        binomial_ci_bs(correct_unpredicted(before_trials_unpredicted))];
    behavior_stats.accuracy.unpredicted.after = ...
        [sum(correct_unpredicted(after_trials_unpredicted))...
        ./sum(after_trials_unpredicted),...
        binomial_ci_bs(correct_unpredicted(after_trials_unpredicted))];
    behavior_stats.accuracy.unpredicted.inhib = ...
        [sum(correct_unpredicted(inhib_trials_unpredicted))...
        ./sum(inhib_trials_unpredicted),...
        binomial_ci_bs(correct_unpredicted(inhib_trials_unpredicted))];
    behavior_stats.accuracy.unpredicted.recov = ...
        [sum(correct_unpredicted(recov_trials_unpredicted))...
        ./sum(recov_trials_unpredicted),...
        binomial_ci_bs(correct_unpredicted(recov_trials_unpredicted))];
    behavior_stats.accuracy.unpredicted.during = ...
        [sum(correct_unpredicted(during_trials_unpredicted))...
        ./sum(during_trials_unpredicted),...
        binomial_ci_bs(correct_unpredicted(during_trials_unpredicted))];
    
    behavior_stats.accuracy.unpredicted.diff.after = ...
        [binomial_compare_bs(correct_trials(before_trials_unpredicted),...
        correct_trials(after_trials_unpredicted))];
    behavior_stats.accuracy.unpredicted.diff.inhib = ...
        [binomial_compare_bs(correct_trials(before_trials_unpredicted),...
        correct_trials(inhib_trials_unpredicted))];
    behavior_stats.accuracy.unpredicted.diff.recov = ...
        [binomial_compare_bs(correct_trials(before_trials_unpredicted),...
        correct_trials(recov_trials_unpredicted))];
    behavior_stats.accuracy.unpredicted.diff.during = ...
        [binomial_compare_bs(correct_trials(before_trials_unpredicted),...
        correct_trials(during_trials_unpredicted))];
    
    behavior_stats.accuracy.unpredicted.diff.all.before = ...
        [binomial_compare_bs(all_before_unpredicted,...
        correct_trials(before_trials_unpredicted))];
    behavior_stats.accuracy.unpredicted.diff.all.after = ...
        [binomial_compare_bs(all_before_unpredicted,...
        correct_trials(after_trials_unpredicted))];
    behavior_stats.accuracy.unpredicted.diff.all.inhib = ...
        [binomial_compare_bs(all_before_unpredicted,...
        correct_trials(inhib_trials_unpredicted))];
    behavior_stats.accuracy.unpredicted.diff.all.recov = ...
        [binomial_compare_bs(all_before_unpredicted,...
        correct_trials(recov_trials_unpredicted))];
    behavior_stats.accuracy.unpredicted.diff.all.during = ...
        [binomial_compare_bs(all_before_unpredicted,...
        correct_trials(during_trials_unpredicted))];
    

    session_stats{n} = behavior_stats;

end

